server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_analysis?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: weiming711
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  thymeleaf:
    cache: false
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stock.model
  configuration:
    map-underscore-to-camel-case: true

stock:
  alpha-vantage-api-key: AZ3II6AA1ZWXL24C
  symbols:
    - SPY
    - QQQ
  schedule:
    cron: "0 0 16 * * ?"  # 每天下午4点执行
  init:
    years: 5  # 初始化5年的数据 