server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/stock_analysis?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: weiming711
    url: jdbc:mysql://online.ctaeaw8a05ny.ap-southeast-2.rds.amazonaws.com:3306/stock_analysis?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: Weiming711
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  thymeleaf:
    cache: false
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stock.model
  configuration:
    map-underscore-to-camel-case: true

stock:
  symbols:
    - SPY
    - QQQ
data:
  init_years: 5
  alpha-vantage-api-key: AZ3II6AA1ZWXL24C